activation: silu
aggr: add
atom_filter: -1
batch_size: 8
coord_files: null
cutoff_lower: 0.0
cutoff_upper: 4.5
dataset: Custom
derivative: true
early_stopping_patience: 300
ema_alpha_neg_dy: 1.0
ema_alpha_y: 0.01
embed_files: null
embedding_dimension: 128
energy_files: null
equivariance_invariance_group: O(3)
y_weight: 0.25
force_files: null
neg_dy_weight: 0.25
gradient_clipping: 40.0
inference_batch_size: 8
load_model: null
log_dir: logs/
lr: 0.001
lr_factor: 0.8
lr_min: 1.0e-08
lr_patience: 25
lr_warmup_steps: 500
max_num_neighbors: 64
max_z: 128
model: tensornet-ext
ngpus: 1
num_epochs: 10000
num_layers: 2
num_nodes: 1
num_rbf: 32
num_workers: 16
output_model: Scalar
precision: 32
prior_model: null
rbf_type: expnorm
redirect: false
reduce_op: add
seed: 12345
save_interval: 10
splits: null
standardize: true
test_interval: 30
test_size: null
train_size: 1000
trainable_rbf: false
val_size: 96
weight_decay: 0.0
esp_weight: 0.25
esp_grad_weight: 0.25
ext_num_rbf: 32
ext_rbf_type: expnorm
ext_trainable_rbf: false
ext_cutoff_lower: 0.0
ext_cutoff_upper: 20.0
