#!/bin/bash
#PBS -q preemptable
#PBS -A EnzymeSim
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=1:ngpus=1
#PBS -l filesystems=home:eagle
#PBS -j oe

date

module load amber/24
cd ${PBS_O_WORKDIR}

cpu="mpirun -n ${NCPUS} pmemd.MPI"
pmemd="pmemd.cuda"
parm="step3_pbcsetup"

# find the right parm file
if [ -f "${parm}_1264.parm7" ]; then
    init="${parm}_1264"
else
    init="${parm}"
fi

pstep="prod00"
istep="prod01"
echo "$pstep $istep"

$pmemd -O -i prod2.mdin \
    -p ${init}.parm7 \
    -c ${pstep}.ncrst \
    -o ${istep}.mdout \
    -r ${istep}.ncrst \
    -inf ${istep}.mdinfo \
    -ref ${init}.ncrst \
    -x ${istep}.nc

date

