#!/bin/bash
#PBS -q preemptable
#PBS -A EnzymeSim
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=1:ngpus=1
#PBS -l filesystems=home:eagle
#PBS -j oe

date

module load amber/24
cd ${PBS_O_WORKDIR}

cpu="mpirun -n ${NCPUS} pmemd.MPI"
pmemd="pmemd.cuda"
parm="step3_pbcsetup"

# find the right parm file
if [ -f "${parm}_1264.parm7" ]; then
    init="${parm}_1264"
else
    init="${parm}"
fi

# min - if CPU fails, then run on cpu with $cpu
$pmemd -i min.mdin -p ${init}.parm7 -c ${init}.rst7 -O -o min.mdout -r min.rst7 -inf min.mdinfo -ref ${init}.rst7 -x min.nc

# Heating
$pmemd -i heat.mdin -p ${init}.parm7 -c min.rst7 -O -o heat.mdout -r heat.rst7 -inf heat.mdinfo -ref ${init}.rst7 -x heat.nc

# Pressure
$pmemd -i density.mdin -p ${init}.parm7 -c heat.rst7 -O -o density.mdout -r density.rst7 -inf density.mdinfo -ref ${init}.rst7 -x density.nc

# NVT
$pmemd -i prod.mdin -p ${init}.parm7 -c density.rst7 -O -o prod00.mdout -r prod00.ncrst -inf prod00.mdinfo -ref ${init}.rst7 -x prod00.nc

date

